# clean up directories before doing anything is a good thing.. aah the fresh smell of clean :)
---

# fixme: this should have checks as it can mean dataloss and downtime
- name: Prune everything in docker
  community.docker.docker_prune:
    containers: true
    images: true
    images_filters:
      dangling: false
    networks: true
    volumes: true
    builder_cache: true
  when: migrid_cleanup == true

- name: "Remove {{ migrid_au_overlay }}"
  file:
    path: "{{ migrid_au_overlay }}"
    state: absent

- name: "Remove {{ migrid_root }}"
  file:
    path: "{{ migrid_root }}"
    state: absent
